# Server Configuration
server:
  port: 8080

spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: Danhviptb12
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhnche171664@fpt.edu.vn
    password: mggu virp mfxv levq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # OAuth2 Google Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-client-secret}
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

# Logging
logging:
  level:
    root: INFO
    com.swp391.team6: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Booking: payment time limit (minutes) for pending bookings
booking:
  payment-expiry-minutes: 5

payos:
  client-id: e5acc5f5-9a5d-4760-ae2c-dddeaaa84de2
  api-key: 871e6d60-2c45-48a8-997e-02e5a7058875
  checksum-key: 9da3fe56a6f65d8301e51a9b980a27addcc328651488916b9bb82cea28a4df04
  base-url: https://api-merchant.payos.vn

# Application URL
app:
  url: http://localhost:8080