# Server Configuration
server:
  port: 8080

spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhnche171664@fpt.edu.vn
    password: mggu virp mfxv levq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # OAuth2 Google Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

# Logging
logging:
  level:
    root: INFO
    com.swp391.team6: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Booking: payment time limit (minutes) for pending bookings
booking:
  payment-expiry-minutes: 5

payos:
  client-id: a752cbb2-005d-4a42-b3f9-b69cc9630e1a
  api-key: f4158278-0608-4943-b318-73bae855c809
  checksum-key: 0f5fe33fba45c5b587c896b093a26abeb2d677d86099a06cbb8c55be2df36ffc
  base-url: https://api-merchant.payos.vn

# Application URL
app:
  url: http://localhost:8080